### ISSUE TITLE
Can this be used to replicate Redis Enterprise tile?

### ISSUE THREAD

**Issue by uvzubovs** [pivotal-cf/replicator#1]
Can this tool be used to replicate Redis Enterprise tile to deploy multiple Redis clusters? I know this tool can be used to replicate Rabbit tile to achieve the same effect.

**Comment by njbennett** [comment]
Hey @uvzubovs , apologies for the delay in replying, are you still working on this?

I would expect this to work, but the fastest way to know for sure would be to try it.
